[
    uuid(E266BF5A-6FB6-4B4F-843C-C34ED7EA598D)
]
library ProxyCopyHandlerLib
{
    interface IProxyCopyHook {
    };

    [
        uuid(4EB17DC6-A98E-42DE-9F3F-93A6819B08A4)
    ]
    coclass ProxyCopyHook {
        [default] interface IProxyCopyHook;
    };
};
